### ISSUE TITLE
cargo install fails

### ISSUE THREAD

**Issue by etnt** [sile/erldash#3]
Trying: cargo install erldash on a Linux machine:

     Compiling erldash v0.1.2                                                                                                                                                                    
     error: there is no argument named `e`                                                                                                                                                          
       --> /home/tobbe/.cargo/registry/src/github.com-1ecc6299db9ec823/erldash-0.1.2/src/erlang.rs:34:55                                                                                            
      |                                                                                                                                                                                           
      34 |                 log::error!("Erlang RPC Client error: {e}");                                                                                                                              
      |                                                       ^^^

**Comment by sile** [comment]
Hmm, what is the rust version you used?
`erldash` uses [the "Captured identifiers in format strings"](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings) introduced in rust-1.58.0 (release date: 2022/01/13). So, if your rust version is older than that, the compile would fail.

BTW, there is a pre-built binary for Linux on the release page (https://github.com/sile/erldash/releases/tag/0.1.2).

**Comment by etnt** [comment]
$ rustc --version
     rustc 1.57.0

btw, I tried to download the linux binary via that curl-call but it couldn't be found.

**Comment by etnt** [comment]
Got it to work now, very cool :+1:
